name: thoga_kade
description: A vegetable shop management system.

publish_to: 'none' # This indicates the app is not for publishing.

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.13.0
  firebase_database: ^10.2.1
  provider: ^6.0.5
  intl: ^0.19.0
  fl_chart: ^0.62.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true # Enables localization generation
  assets:
#    - assets/images/
# Ensure this directory exists
