// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8h4aoiUZ4engl3_42J9aABDFEC8e-mjA',
    appId: '1:648996619467:web:b15940fd9f45430af7c74e',
    messagingSenderId: '648996619467',
    projectId: 'thoga-kade',
    authDomain: 'thoga-kade.firebaseapp.com',
    storageBucket: 'thoga-kade.firebasestorage.app',
    databaseURL: 'https://thoga-kade-default-rtdb.firebaseio.com'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5AOjqFB7QDPfyOB6wU_dcuCzJND0fIcM',
    appId: '1:648996619467:android:f903fabd5b542110f7c74e',
    messagingSenderId: '648996619467',
    projectId: 'thoga-kade',
    storageBucket: 'thoga-kade.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoeMPHCEFYtm4AfOhxmcFG2DKsyr4lIKU',
    appId: '1:648996619467:ios:2c65fe7c4c77889ff7c74e',
    messagingSenderId: '648996619467',
    projectId: 'thoga-kade',
    storageBucket: 'thoga-kade.firebasestorage.app',
    iosBundleId: 'com.example.thogakadeWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoeMPHCEFYtm4AfOhxmcFG2DKsyr4lIKU',
    appId: '1:648996619467:ios:2c65fe7c4c77889ff7c74e',
    messagingSenderId: '648996619467',
    projectId: 'thoga-kade',
    storageBucket: 'thoga-kade.firebasestorage.app',
    iosBundleId: 'com.example.thogakadeWithFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8h4aoiUZ4engl3_42J9aABDFEC8e-mjA',
    appId: '1:648996619467:web:941b1607b9a982d7f7c74e',
    messagingSenderId: '648996619467',
    projectId: 'thoga-kade',
    authDomain: 'thoga-kade.firebaseapp.com',
    storageBucket: 'thoga-kade.firebasestorage.app',
  );
}
